theme: jekyll-theme-slate
title: せし方が分かんないよ
description: this will probably be empty, but idk for how long
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
- jeomoji
url: "https://bohnonloso10.github.io/"
markdown: kramdown
